### PR TITLE
python-minimal no Instalation candidate error solution

### LINKED ISSUE #4: Linux Quick start Error "python-minimal has no installation candidate"
When Ubuntu user try to follow the development environment setup given on https://developer.rocket.chat/guides/developer/quick-start. The first Command  `sudo apt install g++ build-essential git curl python-minimal`  there comes an error "python-minimal has no installation candidate" this is no one command run easy error so we should provide a list of error they can encounter including the above one. I myself encountered the error and spent hours resolving it. So can anyone incorporate the solution there on the guide or you can add this on the possible errors page . I've resolved the issue so you just have to add this to the code.
Solution-  To error "python-minimal has no installation candidate"
1. First run  sudo -i to run commands as root
2. Now make a copy of sources.list file  by   mv /etc/apt/sources.list /etc/apt/sources.list_stor
3. Then update packages  apt-get update
4. Now edit sources.list file 
         * Open file  by vi /etc/apt/sources.list
         * Press i to change into insert mode 
         * Copy paste this inside
              deb http://archive.ubuntu.com/ubuntu​ bionic main restricted universe multiverse
              deb http://archive.ubuntu.com/ubuntu​ bionic-security main restricted universe multiverse
              deb http://archive.ubuntu.com/ubuntu​ bionic-updates main restricted universe multiverse 
              deb http://mirror.kakao.com/ubuntu​ focal-security main restricted
              deb http://mirror.kakao.com/ubuntu​ focal-security universe
              deb http://mirror.kakao.com/ubuntu​ focal-security multiverse
         *  Press shift+esc and type :x and enter to save sources file	
5. Run  apt-get update again.
6. Run apt-get install python 
7. Then  come back to main terminal and run sudo apt install python-minimal.

### PR DESCRIPTION
**Pull request by 4msha**
This will resolve #4 issue. I've added a new file possible-errors.md  where we can add solution to any future errors while installing.

### CODE REVIEW

**Comment by frdmn** [comment]
Hi @4msha! Thanks for working on this. A couple of notes to this PR:

- It seems like you've added a couple of files from your IDE (IntelliJ Idea) to the repo. This is not necessary and should be removed. (`.idea/`)
- Which distribution did you use when working with this guide? It's made specifically for Ubuntu 18.04 LTS and the package in question (`python-minimal`) should be available without any issues out of the box there. 

Feel free to let us know if you still had issues with the recommended OS from the guide.

**Comment by 4msha** [comment]
This error arises on Ubuntu 20.04. So this means this is not an issue.
Maybe we can add a line there if you are using other OS you may run into possible errors. And we have a list of solution to those errors.
errrooorrrrrr

**Comment by engelgabriel** [comment]
@4msha can you please do a pull, and commit your changes again without the `.idea/` folder?

**Review by engelgabriel — CHANGES_REQUESTED** [review]
please do a pull, and commit your changes again without the .idea/ folder?

**Comment by 4msha** [comment]
I've done the requested changes.

**Comment by 4msha** [comment]
Done a pull and removed .idea folder

**Pull request merged**
